const menu = [
  {
    id: 1,
    title: "Buttermilk Panc: Pancakes",
    category: "Breakfast",
    price: 15.99,
    img: "./images/item-1.jpg",
    description: "Fluffy pancakes served with maple syrup and butter",
  },
  {
    id: 2,
    title: "Eggs Benedict",
    category: "Breakfast",
    price: 10.99,
    img: "./images/item-2.jpg",
    description:
      "Poached eggs served on English muffins with ham and hollandaise sauce",
  },
  {
    id: 3,
    title: "Chicken Caesar Salad",
    category: "Lunch",
    price: 12.99,
    img: "./images/item-3.jpg",
    description:
      "Grilled chicken served on romaine lettuce with Caesar dressing",
  },
  {
    id: 4,
    title: "Beef Burger",
    category: "Lunch",
    price: 14.99,
    img: "./images/item-4.jpg",
    description: "Juicy beef burger served with fries and a pickle",
  },
  {
    id: 5,
    title: "Margherita Pizza",
    category: "Dinner",
    price: 16.99,
    img: "./images/item-5.jpg",
    description: "Classic pizza with tomato sauce, mozzarella, and fresh basil",
  },
  {
    id: 6,
    title: "Spaghetti Carbonara",
    category: "Dinner",
    price: 13.99,
    img: "./images/item-6.jpg",
    description: "Spaghetti with creamy egg sauce, pancetta, and Parmesan",
  },
  {
    id: 7,
    title: "Apple Pie",
    category: "Dessert",
    price: 7.99,
    img: "./images/item-7.jpg",
    description: "Warm apple pie served with a scoop of vanilla ice cream",
  },
  {
    id: 8,
    title: "Chocolate Cake",
    category: "Dessert",
    price: 8.99,
    img: "./images/item-8.jpg",
    description: "Rich chocolate cake served with whipped cream",
  },
  {
    id: 9,
    title: "Caesar Salad",
    category: "Salad",
    price: 8.99,
    img: "./images/item-9.jpg",
    description: "Romaine lettuce with Caesar dressing, croutons and Parmesan",
  },
  {
    id: 10,
    title: "Greek Salad",
    category: "Salad",
    price: 9.99,
    img: "./images/item-10.jpg",
    description:
      "Fresh salad with tomatoes, cucumbers, olives, feta, and Greek dressing",
  },
  {
    id: 11,
    title: "French Toast",
    category: "Breakfast",
    price: 11.99,
    img: "./images/item-11.jpg",
    description: "Sweet French toast served with maple syrup and fresh berries",
  },
  {
    id: 12,
    title: "Club Sandwich",
    category: "Lunch",
    price: 12.99,
    img: "./images/item-12.jpg",
    description:
      "Triple-decker sandwich with turkey, bacon, lettuce, and tomato",
  },
  {
    id: 13,
    title: "Chicken Alfredo",
    category: "Dinner",
    price: 14.99,
    img: "./images/item-13.jpg",
    description:
      "Creamy pasta with grilled chicken, Parmesan, and fresh parsley",
  },
  {
    id: 14,
    title: "Cheesecake",
    category: "Dessert",
    price: 7.99,
    img: "./images/item-14.jpg",
    description: "Creamy cheesecake served with a sweet strawberry sauce",
  },
  {
    id: 15,
    title: "Cobb Salad",
    category: "Salad",
    price: 9.99,
    img: "./images/item-15.jpg",
    description:
      "Mixed greens with chicken, bacon, avocado, blue cheese, and hard-boiled egg",
  },
  {
    id: 16,
    title: "Omelette",
    category: "Breakfast",
    price: 10.99,
    img: "./images/item-16.jpg",
    description:
      "Fluffy omelette with your choice of fillings, served with toast",
  },
  {
    id: 17,
    title: "Fish and Chips",
    category: "Lunch",
    price: 13.99,
    img: "./images/item-17.jpg",
    description: "Crispy fried fish served with chips and tartar sauce",
  },
  {
    id: 18,
    title: "Steak Frites",
    category: "Dinner",
    price: 21.99,
    img: "./images/item-18.jpg",
    description: "Grilled steak served with fries and a side salad",
  },
  {
    id: 19,
    title: "Tiramisu",
    category: "Dessert",
    price: 8.99,
    img: "./images/item-19.jpg",
    description:
      "Classic Italian dessert with espresso-soaked ladyfingers and mascarpone cream",
  },
  {
    id: 20,
    title: "Caprese Salad",
    category: "Salad",
    price: 8.99,
    img: "./images/item-20.jpg",
    description:
      "Fresh mozzarella, tomatoes, and basil, drizzled with balsamic reduction",
  },
];
